### PR TITLE
Hdf again

### PR DESCRIPTION
**Pull request by hobu**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hobu** [comment]
@ocefpaf I'm stumped here. The solver works on Windows when I run it locally in a new environment, but it fails in AzP. What could be the discrepancy?

**Comment by hobu** [comment]
I think the issue is the windows pin is GDAL 3.0 instead of 3.1

```
libgdal:
- '3.0'
```

**Comment by ocefpaf** [comment]
> @ocefpaf I'm stumped here. The solver works on Windows when I run it locally in a new environment, but it fails in AzP. What could be the discrepancy?

Sorry. I've been so swamped with other stuff that I forgot about this one.

> I think the issue is the windows pin is GDAL 3.0 instead of 3.1

Could be. I'll put up a migrator for 3.1.

**Comment by ocefpaf** [comment]
Ah. We do have a migrator already and it is stuck b/c of https://github.com/conda-forge/qgis-feedstock/pull/124

**Pull request closed without merging**
