### PR TITLE
Add HDF support per default in build

### PR DESCRIPTION
**Pull request by jomey**
All the requirements are met to have the HDF reader active per default for the conda package. Added the required line to the `build.sh`

### CODE REVIEW

**Comment by jomey** [comment]
@conda-forge-admin, please rerender

**Comment by hobu** [comment]
I don't get why this one is solving. Does HDF need to be rerendered @ocefpaf ?

**Comment by ocefpaf** [comment]
This is probably b/c of the ongoing migration. I'll take a closer look tomorrow and see if we can work around it.

**Comment by hobu** [comment]
> This is probably b/c of the ongoing migration

Ok, thanks for the update. I'll bounce this tomorrow afternoon and see if things have improved.

**Comment by hobu** [comment]
Still not resolving as a result of the bounce. The first complaint is GEOS. Does it maybe need to be rerendered?

**Comment by ocefpaf** [comment]
Do you want do merge this to "cash" Linux and macOS? We can solve the Windows issue once we unstuck gdal 3.1 migration.

**Comment by hobu** [comment]
> Do you want do merge this to "cash" Linux and macOS? We can solve the Windows issue once we unstuck gdal 3.1 migration.

🤷 , I don't really want to have different capabilities enabled on the different platforms. It is fine to wait until GDAL's migration is resolved.

**Comment by jomey** [comment]
Happy to wait on this end too. No pressing need at this point.

**Comment by jomey** [comment]
Any progress on the GDAL migration and get this merged?

**Comment by hobu** [comment]
no, it's still waiting on a conda-build update. I'll start the machine as soon as it is pushed.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
Done in #115

**Pull request closed without merging**
