### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #31.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by hobu** [comment]
@ocefpaf when I try to rerender PDAL, I get 

```
Unsatisfiable dependencies for platform linux-64: {'geos=3.7.1', 'curl=7.59', 'libgdal=2.3'}
```

on most platforms. What needs to be re-rendered? GDAL? I thought the reason we removed all the pins was so this would no longer be an issue?

**Comment by hobu** [comment]
GEOS 3.7.1 was released but the pinning is x.x.x and I think GDAL needs to be rerendered.

@conda-forge-admin, please rerender

**Comment by hobu** [comment]
This depends on https://github.com/conda-forge/gdal-feedstock/pull/256 to get done

**Comment by kmuehlbauer** [comment]
> This depends on [conda-forge/gdal-feedstock#256](https://github.com/conda-forge/gdal-feedstock/pull/256) to get done

https://github.com/conda-forge/gdal-feedstock/pull/256 was just merged. The package should be available in a few hours latest.

**Comment by hobu** [comment]
> Unsatisfiable dependencies for platform linux-64: {'libgdal=2.3', 'geos=3.7.1', 'curl=7.59'}

Unfortunately it still seems to be resolving libgdal 2.3 (which uses geos=3.7.0). I think this is because GDAL is being grabbed from https://anaconda.org/anaconda/gdal rather than https://anaconda.org/conda-forge/gdal

**Comment by mariusvniekerk** [comment]
can you make a pr to the conda-forge pinnings?

**Comment by mariusvniekerk** [comment]
seems like this is not getting the correct linker flags

**Comment by hobu** [comment]
A rerender also ditches the custom settings needed to complete the builds.

**Comment by hobu** [comment]
> seems like this is not getting the correct linker flags

Nothing has changed between PDAL's use of GDAL 2.3 vs. 2.4. Did something change in how GDAL links libxml and GEOS in 2.4?

**Comment by hobu** [comment]
Is there a bug with conda's rpath munging? PDAL is trying to link to 

```
`/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/work/lib:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::` 
```

This directory of course is not found. 

```
/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++  -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -std=c++11 -O3 -DNDEBUG  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -L/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib -rdynamic CMakeFiles/pdal.dir/pdal.cpp.o  -o ../bin/pdal -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/work/lib::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: ../lib/libpdal_base.so.8.0.0 ../lib/libpdal_util.so.8.0.0 -ljsoncpp -lgdal
/home/conda/feedstock_root/build_artifacts/pdal_1548044209272/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libgeos_c.so.1, needed by ../lib/libpdal_base.so.8.0.0, not found (try using -rpath or -rpath-link)
```

**Pull request merged**
