### PR TITLE
Fix PDAL_PYTHON_PATH from abspath to relative to allow loading of readers.numpy

### PR DESCRIPTION
**Pull request by hobu**
`readers.numpy` does not currently work on conda builds due to Python library loading issue.

### CODE REVIEW

**Comment by hobu** [comment]
@ocefpaf We can't resolve `nitro` and `pcl` here even though I had recently regenerated them both. I don't immediately understand what could be the issue. PCL might have some hairy dependencies related to HDF and such, but nitro has no dependencies. Could it be a labeling issue?

https://anaconda.org/conda-forge/pcl
https://anaconda.org/conda-forge/nitro

**Comment by ocefpaf** [comment]
@hobu in #56 things are working as expected and I think I got most of your changes here. (I added a few minor recipe fixes and did not port the license rename b/c we need the full license with the version.)

Can you take a look at #56 and, if that is OK, merge that instead of this one?

**Comment by hobu** [comment]
Are all of the azure failures false? There's no OSX or Linux build succeeding in this PR, which is the problem I was having before with the resolution.

Thanks for the licensing fix. I didn't know what the proper way to achieve that was, but the recipe kept emitting a warning about what was there previously.

**Comment by ocefpaf** [comment]
> Are all of the azure failures false? There's no OSX or Linux build succeeding in this PR, which is the problem I was having before with the resolution.

Nope. They are true failures. Not sure why #56 is passing though :smile:

**Pull request closed without merging**
