### PR TITLE
Attempt to split into multiple packages

### PR DESCRIPTION
**Pull request by hobu**
For the upcoming PDAL 2.6.0, we have added the ability to conveniently build `-DSTANDALONE=ON` plugins that have external library dependencies. This should allow us to split the conda package into something like this:

* libpdal (base library and command line utilities, same as libgdal)
* pdal-trajectory
* pdal-tiledb
* pdal-draco
* pdal-hdf
* pdal-nitf
* pdal-pgpointcloud
* pdal <-- installs python-pdal stuff and everything else :point_up:

It's not quite working and of course points to the unreleased PDAL 2.6.0 branch but I want to make sure it can work before releasing 2.6.0.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Multiple outputs can be complex but at a first glance everything looks good here. I'm not the best person to say b/c we need to know how the downstream packages and users are using pdal. for example, someone that expects to just `conda install pdal`  seems to be covered. The ones that may want `pdal-*` will need docs/warnings.

The most complex one are packaging that are building using pdal but from now on would be OK with libpdal only. Those will require a pin to ensure they'll get the right combo of pdal/libpdal. (Image building with one version of libpdal but, if we forget to pin things correctly, install it with an older pdal.)

**Comment by hobu** [comment]
A couple more points to add.

* Unlike GDAL, what is currently `python-pdal` is released on a different schedule than the base `libpdal` library
* For PDAL 2.6.0 we will implement the package splitting in this PR
* We will wait for the next [PDAL Python](https://github.com/PDAL/python/) release to rename the `python-pdal` conda forge package to `pdal`
* How should we update pins to protect this from falling apart 😄 ?

**Comment by ocefpaf** [comment]
> * How should we update pins to protect this from falling apart 😄 ?

Let's say that from now on you only want folks building against pdal 2.6.0, unless they explicitly require an older version, you should mimic `gdal`/`libgdal` pins in: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

PS: Hey @isuruf I know you are super busy lately with the Windows arm stuff but if you find some spare time do you mind taking a look at this PR?

**Comment by isuruf** [comment]
Add
```
conda_build:
  error_overlinking: true
```

to `conda-forge.yml` and this build would error. You should fix the dependencies so that the build passes again.

**Pull request closed without merging**
